// <auto-generated />
using System;
using AppCadastroPessoasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppCadastroPessoasAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Entities.Calendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("PrimeiroDiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Calendario");
                });

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Entities.DataEspecificaCalendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarioId")
                        .HasColumnType("int");

                    b.Property<int>("Dia")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalendarioId");

                    b.ToTable("DatasEspecificas");
                });

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Entities.DiaSemanaCalendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarioId");

                    b.ToTable("DiasSemana");
                });

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Entities.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DataEspecificaCalendarioId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("DiaSemanaCalendarioId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Hora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vagas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DataEspecificaCalendarioId");

                    b.HasIndex("DiaSemanaCalendarioId");

                    b.ToTable("Horarios");
                });

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Pessoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Entities.DataEspecificaCalendario", b =>
                {
                    b.HasOne("AppCadastroPessoasAPI.Models.Entities.Calendario", "Calendario")
                        .WithMany("DatasEspecificas")
                        .HasForeignKey("CalendarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendario");
                });

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Entities.DiaSemanaCalendario", b =>
                {
                    b.HasOne("AppCadastroPessoasAPI.Models.Entities.Calendario", "Calendario")
                        .WithMany("DiasSemana")
                        .HasForeignKey("CalendarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendario");
                });

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Entities.Horario", b =>
                {
                    b.HasOne("AppCadastroPessoasAPI.Models.Entities.DataEspecificaCalendario", "DataEspecificaCalendario")
                        .WithMany("Horarios")
                        .HasForeignKey("DataEspecificaCalendarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppCadastroPessoasAPI.Models.Entities.DiaSemanaCalendario", "DiaSemanaCalendario")
                        .WithMany("Horarios")
                        .HasForeignKey("DiaSemanaCalendarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataEspecificaCalendario");

                    b.Navigation("DiaSemanaCalendario");
                });

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Entities.Calendario", b =>
                {
                    b.Navigation("DatasEspecificas");

                    b.Navigation("DiasSemana");
                });

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Entities.DataEspecificaCalendario", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("AppCadastroPessoasAPI.Models.Entities.DiaSemanaCalendario", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
